version: "3.8"
services:
  app:
    volumes:
      - ./:/opt/app:delegated
      - node_modules:/opt/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
volumes:
  node_modules: